. run_reco_new.sh 0.5
. run_reco_new.sh 1.0
. run_reco_new.sh 1.5
. run_reco_new.sh 2.0
. run_reco_new.sh 2.5
. run_reco_new.sh 3.0
. run_reco_new.sh 3.5
. run_reco_new.sh 4.0
. run_reco_new.sh 4.5
. run_reco_new.sh 5.0
. run_reco_new.sh 5.5
. run_reco_new.sh 6.0
